mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('polls/', views.IndexView.as_view(), name='index'),
    path('polls/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('polls/<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('polls/<int:question_id>/vote/', views.vote, name='vote'),
    path('polls/<int:question_id>/pie_chart/', views.pie_chart, name='pie_chart'),
]

polls/models.py
from django.db import models
from django.contrib import admin

import datetime

# Create your models here.
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Fecha de publicacion')
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def __str__(self):
        return self.question_text
    """Ahora las fechas a futuro darán falso ya que no son recientes"""
    def was_published_recently(self):
    	now = timezone.now()
    	return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

def pie_chart(request, question_id):
    labels = []
    data = []
    #queryset = Question.objects.get(id=question_id).choice_set.all()
    #q = Question.objects.get(id=question_id)
    #queryset = Choice.objects.filter(question = q)
    
    queryset = Choice.objects.filter(question__id=question_id)
    
    for choice in queryset:
        labels.append(choice.choice_text)
        data.append(choice.votes)
    return render(request, 'polls/pie_chart.html', {
        'labels': labels,
        'data': data,
    	})

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'
	
	def get_queryset(self):
		#Devuelve las cinco ultimas encuestas realizadas
		#Con objects.filter evitamos que se muestren las encuestas que estan con fechas futuras
		return Question.objects.filter(
			pub_date__lte=timezone.now()
		).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		"""
		Excluye cualquier pregunta que no han sido publicadas aun
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

#Funcion de votacion
def vote(request, question_id):
    #Intentara encontrar el objeto y, encaso de de que no lo encuentre nos mostrara un error
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        #Volver a mostrar el formulario de votación de preguntas
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "No has seleccionado una opción.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Siempre devuelva un HttpResponseRedirect después de manejar con
        # éxito los datos POST. Esto evita que los datos se publiquen dos 
        # veces si un usuario presiona el botón Atrás.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

"""Estas son las antiguas vistas que tenia aplicadas
#Muestra una plantilla con las cinco ultimas encuestas publicadas
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
"""
"""
#Funcion de detalles
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
"""
"""
#Funcion para ver los resultados
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
"""

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<p><button type="submit" value="Votar"><b>Votar</b></button></p>
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
<title>Pregunta</title>
</head>
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<body align = center>
<h1 style="color:green;">Preguntas más recientes</h1>
{% if latest_question_list %}

    <ul>
    {% for question in latest_question_list %}
	
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay encuestas actualmente.</p>
{% endif %}
</html>

polls/templates/polls/pie_chart.html
<!--{#{% extends 'base.html' %}#}-->
<!--Extiende de una plantilla que el usuario ya tiene preparada no debo fiarme. Debo seguir estuadiando
<!--{#{% block content %}#}-->
  <div id="container" style="width: 75%;">
    <canvas id="pie_chart"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
            '#759eff', '#9375ff', '#75e1ff'
          ],
          label: 'Question'
        }],
        labels: {{ labels|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie_chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>

<!--{#{% endblock %}#}-->

polls/templates/polls/results.html
<html>
<head>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{choice.votes}} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">¿Votar de nuevo?</a>
<a href="{% url 'polls:pie_chart' question.id %}">Ver detalles</a>
</body>
</html>

polls/templates/polls/stats.html
<canvas id="myChart" width="600" height="250"  ></canvas>